export default {
    BUILD_NUM: 'BUILD_NUM',
    PORT: 'PORT',

    MSSQLDB_HOST: 'MSSQLDB_HOST',
    MSSQLDB_DBNAME: 'MSSQLDB_DBNAME',
    MSSQLDB_USER: 'MSSQLDB_USER',
    MSSQLDB_PASSWORD: 'MSSQLDB_PASSWORD',

    MONGODB_CONNSTR: 'MONGODB_CONNSTR',
    MONGODB_HOST: 'MONGODB_HOST',
    MONGODB_PORT: 'MONGODB_PORT',
    MONGODB_DBNAME: 'MONGODB_DBNAME',
    MONGODB_USER: 'MONGODB_USER',
    MONGODB_PASSWORD: 'MONGODB_PASSWORD',
    SECRET_KEY: 'SECRET_KEY'
};